### ISSUE TITLE
bean的循环依赖会直接导致StackOverflowError

### ISSUE THREAD

**Issue by coderbruis** [CoderLCSY/datatranslate#1]
大佬，在Spring中，不是已经通过“三层缓存机制”解决了bean的循环依赖问题么？你这里指的循环依赖是什么？

**Comment by waliccc** [comment]
这里的提到的bean的循环依赖，并非springbean的循环依赖，而是多个bean的循环嵌套，循环嵌套会导致递归翻译没有出口
